name: Unzip and Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # জিপ ফাইল আনজিপ করা এবং ফাইলগুলোকে মেইন ফোল্ডারে আনা
      - name: Unzip Source Code
        run: |
          unzip secure-share.zip -d extracted_files
          cp -r extracted_files/* . || true
          cp -r extracted_files/.* . || true

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradlew ফাইল মিসিং থাকলে গিটহাব নিজেই নতুন ফাইল বানিয়ে নেবে
      - name: Validate Gradle Wrapper
        run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: secure-share-app
          path: app/build/outputs/apk/debug/app-debug.apk
